### ISSUE TITLE
crash audio_service when add  flutter_audio_query to pubspec.yaml

### ISSUE THREAD

**Issue by o4x** [sc4v3ng3r/flutter_audio_query#19]
### Everything works fine

but when  I add `flutter_audio_query: "^ 0.3.4 + 1"`  to `pubspec.yaml`

and then click to stop button i get this error :

```
E/MethodChannel#ryanheise.com/audioServiceBackground(26360): Failed to handle method call
E/MethodChannel#ryanheise.com/audioServiceBackground(26360): java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.embedding.engine.plugins.activity.ActivityPluginBinding.removeRequestPermissionsResultListener(io.flutter.plugin.common.PluginRegistry$RequestPermissionsResultListener)' on a null object reference
E/MethodChannel#ryanheise.com/audioServiceBackground(26360): 	at boaventura.com.devel.br.flutteraudioquery.FlutterAudioQueryPlugin.tearDown(FlutterAudioQueryPlugin.java:205)
E/MethodChannel#ryanheise.com/audioServiceBackground(26360): 	at boaventura.com.devel.br.flutteraudioquery.FlutterAudioQueryPlugin.onDetachedFromEngine(FlutterAudioQueryPlugin.java:135)
E/MethodChannel#ryanheise.com/audioServiceBackground(26360): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.remove(FlutterEnginePluginRegistry.java:244)
E/MethodChannel#ryanheise.com/audioServiceBackground(26360): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.remove(FlutterEnginePluginRegistry.java:252)
E/MethodChannel#ryanheise.com/audioServiceBackground(26360): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.removeAll(FlutterEnginePluginRegistry.java:260)
E/MethodChannel#ryanheise.com/audioServiceBackground(26360): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.destroy(FlutterEnginePluginRegistry.java:116)
E/MethodChannel#ryanheise.com/audioServiceBackground(26360): 	at io.flutter.embedding.engine.FlutterEngine.destroy(FlutterEngine.java:267)
E/MethodChannel#ryanheise.com/audioServiceBackground(26360): 	at com.ryanheise.audioservice.AudioServicePlugin$BackgroundHandler.onMethodCall(AudioServicePlugin.java:677)
E/MethodChannel#ryanheise.com/audioServiceBackground(26360): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
E/MethodChannel#ryanheise.com/audioServiceBackground(26360): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
E/MethodChannel#ryanheise.com/audioServiceBackground(26360): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
E/MethodChannel#ryanheise.com/audioServiceBackground(26360): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#ryanheise.com/audioServiceBackground(26360): 	at android.os.MessageQueue.next(MessageQueue.java:376)
E/MethodChannel#ryanheise.com/audioServiceBackground(26360): 	at android.os.Looper.loop(Looper.java:244)
E/MethodChannel#ryanheise.com/audioServiceBackground(26360): 	at android.app.ActivityThread.main(ActivityThread.java:6706)
E/MethodChannel#ryanheise.com/audioServiceBackground(26360): 	at java.lang.reflect.Method.invoke(Native Method)


```

Also https://github.com/ryanheise/audio_service/issues/203

This is basic code 

```

import 'dart:async';

import 'package:flutter/material.dart';
import 'package:audio_service/audio_service.dart';
import 'package:just_audio/just_audio.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);



  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  void initState() {
    super.initState();
    AudioService.connect();
  }


  @override
  Widget build(BuildContext context) {

    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _shuffle,
        child: Icon(Icons.shuffle),
      ),
    );
  }

  _shuffle() async {
    if(! await AudioService.running){
    await AudioService.start(        // When user clicks button to start playback
      backgroundTaskEntrypoint: myBackgroundTaskEntrypoint,
      androidNotificationChannelName: 'Music Player',
      androidNotificationIcon: "mipmap/ic_launcher",
      enableQueue: true,
      androidStopForegroundOnPause: true,
      androidStopOnRemoveTask: true,
      shouldPreloadArtwork: true,
    );
  }
  await AudioService.addQueueItem(
    MediaItem(
      id: '/storage/emulated/0/Downloads/Imagine Dragons - Bad Liar.mp3',
      album: 'test',
      title: 'test',
      artUri: "${Uri.file('/storage/emulated/0/Android/data/com.android.providers.media/albumthumbs/1582602080590')}"
    )
  );
  }


}


void myBackgroundTaskEntrypoint() {
  AudioServiceBackground.run(() => CustomAudioPlayer());
}

class CustomAudioPlayer extends BackgroundAudioTask {
final _queue = <MediaItem>[];
  int _queueIndex = -1;
  AudioPlayer _audioPlayer = new AudioPlayer();
  Completer _completer = Completer();
  BasicPlaybackState _skipState;
  bool _playing;

  bool get hasNext => _queueIndex + 1 < _queue.length;

  bool get hasPrevious => _queueIndex > 0;

  MediaItem get mediaItem => _queue[_queueIndex];

  BasicPlaybackState _stateToBasicState(AudioPlaybackState state) {
    switch (state) {
      case AudioPlaybackState.none:
        return BasicPlaybackState.none;
      case AudioPlaybackState.stopped:
        return BasicPlaybackState.stopped;
      case AudioPlaybackState.paused:
        return BasicPlaybackState.paused;
      case AudioPlaybackState.playing:
        return BasicPlaybackState.playing;
      case AudioPlaybackState.connecting:
        return _skipState ?? BasicPlaybackState.connecting;
      case AudioPlaybackState.completed:
        return BasicPlaybackState.stopped;
      default:
        throw Exception("Illegal state");
    }
  }

  @override
  Future<void> onStart() async {
    var playerStateSubscription = _audioPlayer.playbackStateStream
        .where((state) => state == AudioPlaybackState.completed)
        .listen((state) {
      _handlePlaybackCompleted();
    });
    var eventSubscription = _audioPlayer.playbackEventStream.listen((event) {
      final state = _stateToBasicState(event.state);
      if (state != BasicPlaybackState.stopped) {
        _setState(
          state: state,
          position: event.position.inMilliseconds,
        );
      }
    });

    AudioServiceBackground.setQueue(_queue);
    await _completer.future;
    await playerStateSubscription.cancel();
    await eventSubscription.cancel();
  }

  void _handlePlaybackCompleted() {
    if (hasNext) {
      onSkipToNext();
    } else {
      onStop();
    }
  }

  void playPause() {
    if (AudioServiceBackground.state.basicState == BasicPlaybackState.playing)
      onPause();
    else
      onPlay();
  }

  @override
  Future<void> onSkipToNext() => _skip(1);

  @override
  Future<void> onSkipToPrevious() => _skip(-1);

  Future<void> _skip(int offset) async {
    final newPos = _queueIndex + offset;
    if (!(newPos >= 0 && newPos < _queue.length)) return;
    if (_playing == null) {
      // First time, we want to start playing
      _playing = true;
    } else if (_playing) {
      // Stop current item
      await _audioPlayer.stop();
    }
    // Load next item
    _queueIndex = newPos;
    AudioServiceBackground.setMediaItem(mediaItem);
    _skipState = offset > 0
        ? BasicPlaybackState.skippingToNext
        : BasicPlaybackState.skippingToPrevious;
    await _audioPlayer.setFilePath(mediaItem.id);
    _skipState = null;
    // Resume playback if we were playing
    if (_playing) {
      onPlay();
    } else {
      _setState(state: BasicPlaybackState.paused);
    }
  }

  @override
  void onPlay() async {
    if (_skipState == null) {
      _playing = true;
      _audioPlayer.play();
    }
  }

  @override
  void onPause() {
    if (_skipState == null) {
      _playing = false;
      _audioPlayer.pause();
    }
  }

  @override
  void onSeekTo(int position) {
    _audioPlayer.seek(Duration(milliseconds: position));
  }

  @override
  void onClick(MediaButton button) {
    playPause();
  }

  @override
  void onStop() {
    _audioPlayer.stop();
    _setState(state: BasicPlaybackState.stopped);
    _completer.complete();
  }


  
  @override
  void onAddQueueItem(MediaItem mediaItem) async {
    _queue.add(mediaItem);
    AudioServiceBackground.setQueue(_queue);
    await onSkipToNext();
  }

  void _setState({@required BasicPlaybackState state, int position}) {
    if (position == null) {
      position = _audioPlayer.playbackEvent.position.inMilliseconds;
    }
    AudioServiceBackground.setState(
      controls: getControls(state),
      systemActions: [MediaAction.seekTo],
      basicState: state,
      position: position,
    );
  }

  List<MediaControl> getControls(BasicPlaybackState state) {
    if (_playing) {
      return [
        skipToPreviousControl,
        pauseControl,
        stopControl,
        skipToNextControl
      ];
    } else {
      return [
        skipToPreviousControl,
        playControl,
        stopControl,
        skipToNextControl
      ];
    }
  }

}


MediaControl playControl = MediaControl(
  androidIcon: 'drawable/ic_action_play_arrow',
  label: 'Play',
  action: MediaAction.play,
);
MediaControl pauseControl = MediaControl(
  androidIcon: 'drawable/ic_action_pause',
  label: 'Pause',
  action: MediaAction.pause,
);
MediaControl skipToNextControl = MediaControl(
  androidIcon: 'drawable/ic_action_skip_next',
  label: 'Next',
  action: MediaAction.skipToNext,
);
MediaControl skipToPreviousControl = MediaControl(
  androidIcon: 'drawable/ic_action_skip_previous',
  label: 'Previous',
  action: MediaAction.skipToPrevious,
);
MediaControl stopControl = MediaControl(
  androidIcon: 'drawable/ic_action_stop',
  label: 'Stop',
  action: MediaAction.stop,
);



```

**Comment by sc4v3ng3r** [comment]
Hello @o4x try use `flutter_audio_query: ^0.3.4+2` version. Take a look [here](https://pub.dev/packages/flutter_audio_query#-changelog-tab-)

**Comment by o4x** [comment]
Hi @sc4v3ng3r , thanks for your speed . The new version also has this problem

**Comment by ali-alizadeh** [comment]
Hi @o4x , I was facing this issue too, for the moment the only way I found was using version 0.3.3 instead of the newest version. Just make sure not to use ^ before the version so pub uses exactly the version I mentioned and not a newer one.

**Comment by o4x** [comment]
@Ali-Alizadeh, When I use version `0.3.3` I get this problem

```
Exception has occurred.
MissingPluginException (MissingPluginException(No implementation found for method getSongsById on channel boaventura.com.devel.br.flutteraudioquery))

```

**Comment by de7miii** [comment]
Hi @sc4v3ng3r, I encountered the same problem when using `audio_service`  with `flutter_audio_query 0.3.4+2` and was able to fix it by adding a few lines to the source code.

The problem appears to be that `tearDown()` function is calling functions on null objects of `m_activityBinding`, `channel`, and `application`.

```log
E/MethodChannel#ryanheise.com/audioServiceBackground(26360): Failed to handle method call
E/MethodChannel#ryanheise.com/audioServiceBackground(26360): java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.embedding.engine.plugins.activity.ActivityPluginBinding.removeRequestPermissionsResultListener(io.flutter.plugin.common.PluginRegistry$RequestPermissionsResultListener)' on a null object reference
E/MethodChannel#ryanheise.com/audioServiceBackground(26360): 	at boaventura.com.devel.br.flutteraudioquery.FlutterAudioQueryPlugin.tearDown(FlutterAudioQueryPlugin.java:205)
E/MethodChannel#ryanheise.com/audioServiceBackground(26360): 	at boaventura.com.devel.br.flutteraudioquery.FlutterAudioQueryPlugin.onDetachedFromEngine(FlutterAudioQueryPlugin.java:135)
```

### The Fix
```java
private void tearDown() {
      if(m_activityBinding != null){
          m_activityBinding.removeRequestPermissionsResultListener(m_delegate);
          m_activityBinding = null;
      }
      if (lifecycle != null) {
          lifecycle.removeObserver(observer);
          lifecycle = null;
      }
      m_delegate = null;
      if(channel != null){
          channel.setMethodCallHandler(null);
          channel = null;
      }
      if(application != null){
          application.unregisterActivityLifecycleCallbacks(observer);
          application = null;
      }
    }
```

After changing the source code of the plugin in the project I'm working on it works as expected now with no errors.

I have submitted a pull request with this fix.
