### ISSUE TITLE
Error while using getSongsByArtist() method in Android 10

### ISSUE THREAD

**Issue by pedrolemoz** [sc4v3ng3r/flutter_audio_query#29]
Hello. I'm in Android 10 with ARM64 architecture. When I use the `getSongsByArtist()` method, I get the following:

```
E/AndroidRuntime( 1836): FATAL EXCEPTION: AsyncTask #1
E/AndroidRuntime( 1836): Process: com.pedrolemoz.music_player, PID: 1836
E/AndroidRuntime( 1836): java.lang.RuntimeException: An error occurred while executing doInBackground()
E/AndroidRuntime( 1836):        at android.os.AsyncTask$4.done(AsyncTask.java:399)
E/AndroidRuntime( 1836):        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
E/AndroidRuntime( 1836):        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
E/AndroidRuntime( 1836):        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
E/AndroidRuntime( 1836):        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
E/AndroidRuntime( 1836):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime( 1836):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime( 1836):        at java.lang.Thread.run(Thread.java:919)
E/AndroidRuntime( 1836): Caused by: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: AsyncTask #1
E/AndroidRuntime( 1836):        at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:781)
E/AndroidRuntime( 1836):        at io.flutter.embedding.engine.FlutterJNI.invokePlatformMessageResponseCallback(FlutterJNI.java:718)
E/AndroidRuntime( 1836):        at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:144)
E/AndroidRuntime( 1836):        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:236)
E/AndroidRuntime( 1836):        at boaventura.com.devel.br.flutteraudioquery.loaders.SongLoader$SongTaskLoad.basicLoad(SongLoader.java:454)
E/AndroidRuntime( 1836):        at boaventura.com.devel.br.flutteraudioquery.loaders.SongLoader$SongTaskLoad.loadData(SongLoader.java:374)
E/AndroidRuntime( 1836):        at boaventura.com.devel.br.flutteraudioquery.loaders.SongLoader$SongTaskLoad.loadData(SongLoader.java:330)
E/AndroidRuntime( 1836):        at boaventura.com.devel.br.flutteraudioquery.loaders.tasks.AbstractLoadTask.doInBackground(AbstractLoadTask.java:45)
E/AndroidRuntime( 1836):        at boaventura.com.devel.br.flutteraudioquery.loaders.tasks.AbstractLoadTask.doInBackground(AbstractLoadTask.java:12)
E/AndroidRuntime( 1836):        at android.os.AsyncTask$3.call(AsyncTask.java:378)
E/AndroidRuntime( 1836):        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AndroidRuntime( 1836):        ... 4 more
I/flutter ( 1836): Instance of 'Future<dynamic>'
I/System.out( 1836): SongLoader::basicLoad java.lang.IllegalArgumentException: the bind value at index 1 is null
I/Process ( 1836): Sending signal. PID: 1836 SIG: 9
Lost connection to device.
```

I wonder if any solution is avaliable.

**Comment by sc4v3ng3r** [comment]
fixed #37
