### ISSUE TITLE
exception when working with Playlists on Android 10

### ISSUE THREAD

**Issue by stahlmagnat** [sc4v3ng3r/flutter_audio_query#32]
We like this package, are you still working on it?

Anyone knows a workaround for getting playlist works on Android 10?

Please see:
https://issuetracker.google.com/issues/147619577

"has no access to content"

E/MethodChannel#boaventura.com.devel.br.flutteraudioquery(10506): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#boaventura.com.devel.br.flutteraudioquery(10506): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#boaventura.com.devel.br.flutteraudioquery(10506): 	at android.os.Looper.loop(Looper.java:174)
E/MethodChannel#boaventura.com.devel.br.flutteraudioquery(10506): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/MethodChannel#boaventura.com.devel.br.flutteraudioquery(10506): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#boaventura.com.devel.br.flutteraudioquery(10506): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/MethodChannel#boaventura.com.devel.br.flutteraudioquery(10506): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/flutter (10506): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, com.vsoft.dia has no access to content://media/external_primary/audio/media/29, null)
E/flutter (10506): #0      StandardMethodCodec.decodeEnvelope 
package:flutter/…/services/message_codecs.dart:569
E/flutter (10506): #1      MethodChannel._invokeMethod

**Comment by stahlmagnat** [comment]
is it possible to exclude media located on externalStorage when Android=10 ?
